import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f3f0f0",
        "on-error": "#ffffff",
        "canvas": "#ffffff",
        "background": "#fcf8f9",
        "primary-fixed": "#dee2ef",
        "on-surface-variant": "#45474b",
        "link": "#1b61c9",
        "primary-fixed-dim": "#c2c6d3",
        "inverse-surface": "#313031",
        "hairline": "#dddddd",
        "surface-variant": "#e5e2e2",
        "surface-bright": "#fcf8f9",
        "on-primary-fixed-variant": "#424751",
        "secondary-fixed-dim": "#c2c6d1",
        "on-secondary-container": "#60656d",
        "signature-coral": "#aa2d00",
        "inverse-primary": "#c2c6d3",
        "on-tertiary-fixed-variant": "#524535",
        "on-secondary": "#ffffff",
        "secondary-container": "#dee2ed",
        "surface-soft": "#f8fafc",
        "on-tertiary-container": "#928270",
        "signature-mustard": "#d9a441",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#808590",
        "tertiary-container": "#251b0e",
        "tertiary": "#050200",
        "surface-strong": "#e0e2e6",
        "signature-mint": "#a8d8c4",
        "tertiary-fixed-dim": "#d6c3af",
        "outline": "#76777c",
        "surface-container-low": "#f6f3f3",
        "on-error-container": "#93000a",
        "primary": "#000208",
        "signature-peach": "#fcab79",
        "on-secondary-fixed-variant": "#42474f",
        "signature-yellow": "#f4d35e",
        "secondary": "#5a5f67",
        "outline-variant": "#c6c6cc",
        "primary-container": "#181d26",
        "on-primary": "#ffffff",
        "border-strong": "#9297a0",
        "on-surface": "#1c1b1c",
        "on-secondary-fixed": "#171c23",
        "tertiary-fixed": "#f3dfca",
        "surface-dim": "#dcd9da",
        "surface-container": "#f0edee",
        "success": "#006400",
        "on-tertiary-fixed": "#241a0d",
        "surface-container-high": "#ebe7e8",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5a5e69",
        "on-primary-fixed": "#171c25",
        "surface": "#fcf8f9",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e5e2e2",
        "on-background": "#1c1b1c",
        "signature-forest": "#0a2e0e",
        "secondary-fixed": "#dee2ed",
        "error": "#ba1a1a",
        "ink": "#181d26",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        xxl: "48px",
        sm: "12px",
        section: "96px",
        lg: "24px",
        md: "16px",
        xxs: "4px",
        xs: "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        legal: ["13.12px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["16px", { lineHeight: "1.4", fontWeight: "500" }],
        caption: ["14px", { lineHeight: "1.35", letterSpacing: "0.16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.25", fontWeight: "400" }],
        "display-md": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "1.1", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        "title-lg": ["24px", { lineHeight: "1.35", letterSpacing: "0.12px", fontWeight: "400" }],
        button: ["16px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
